version: '3'
services:
    nginx:
        container_name: "compose-nginx"
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
#            - "443:443"
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - "../nginx/conf.d:/etc/nginx/conf.d"
            - "../nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
            - "/Users/tony/code:/usr/share/nginx/html"
            - "../nginx/log:/var/log/nginx/"
        networks:
            app_net:
                ipv4_address: 10.10.10.2
    mysql:
        platform: linux/x86_64
        image: mysql:5.7
        ports:
            - "33060:3306"
        volumes:
            - "../mysql/data:/var/lib/mysql"
            - "../mysql/conf:/etc/mysql/conf.d"
            - "../mysql/logs:/data/mysql/logs"
        restart: always
        environment:
            - TZ=Asia/Shanghai
            - MYSQL_USER=homestead
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=root123
            - MYSQL_ROOT_HOST="%"
        networks:
            app_net:
                ipv4_address: 10.10.10.1
        container_name: "compose-mysql"
    mysql8:
        platform: linux/x86_64
        image: mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "33070:3306"
        volumes:
            - "../mysql8/data:/var/lib/mysql"
            - "../mysql8/my.cnf:/etc/mysql/conf.d/my.cnf"
            - "../mysql8/logs:/data/mysql/logs"
        restart: always
        environment:
            - TZ=Asia/Shanghai
            - MYSQL_USER=homestead
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=root123
            - MYSQL_ROOT_HOST="%"
        networks:
            app_net:
                ipv4_address: 10.10.10.3
        container_name: "compose-mysql8"
    redis:
        image: redis:latest
        restart: always
        ports:
            - 6379:6379
        volumes:
            - "../redis/conf:/usr/local/etc/redis"
            - "../redis/data:/data"
        command:
          redis-server /usr/local/etc/redis/redis.conf --requirepass root123
        environment:
            - TZ=Asia/Shanghai
        container_name: "compose-redis"
networks:
    app_net:
        driver: bridge
        driver_opts:
          com.docker.network.enable_ipv6: "true"
        ipam:
            config:
                - subnet: 10.10.0.0/16
